# Generated by Django 5.0.2 on 2025-08-21 06:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('expense_type', models.CharField(choices=[('one_time', 'One Time'), ('recurring', 'Recurring'), ('subscription', 'Subscription')], default='one_time', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('mobile_payment', 'Mobile Payment'), ('check', 'Check'), ('other', 'Other')], default='cash', max_length=20)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20, null=True)),
                ('recurring_end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField()),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='expenses.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense Reminder',
                'verbose_name_plural': 'Expense Reminders',
                'ordering': ['reminder_date', 'reminder_time'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_favorite', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_templates', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense Template',
                'verbose_name_plural': 'Expense Templates',
                'ordering': ['-is_favorite', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'date'], name='expenses_ex_user_id_713a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', 'date'], name='expenses_ex_categor_9e3535_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['amount', 'date'], name='expenses_ex_amount_1f1298_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expensetemplate',
            unique_together={('name', 'user')},
        ),
    ]
