# Generated by Django 5.0.2 on 2025-08-21 06:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('knowledge_type', models.CharField(choices=[('faq', 'Frequently Asked Question'), ('tip', 'Budgeting Tip'), ('rule', 'Budgeting Rule'), ('example', 'Example'), ('definition', 'Definition')], default='tip', max_length=20)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1, help_text='Priority for matching (1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chatbot Knowledge',
                'verbose_name_plural': 'Chatbot Knowledge',
                'ordering': ['-priority', '-usage_count'],
                'indexes': [models.Index(fields=['knowledge_type', 'category'], name='chatbot_cha_knowled_6092ba_idx'), models.Index(fields=['is_active', 'priority'], name='chatbot_cha_is_acti_838a9f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('user_preferences', models.JSONField(blank=True, default=dict)),
                ('message_count', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_count', models.IntegerField(default=0)),
                ('session_duration', models.DurationField(blank=True, null=True)),
                ('satisfaction_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField(blank=True)),
                ('response_time', models.DurationField(blank=True, null=True)),
                ('accuracy_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_analytics', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='chatbot.chatsession')),
            ],
            options={
                'verbose_name': 'Chatbot Analytics',
                'verbose_name_plural': 'Chatbot Analytics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('bot', 'Bot Message'), ('system', 'System Message')], default='user', max_length=20)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('is_processed', models.BooleanField(default=False)),
                ('ai_response', models.TextField(blank=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence score (0-1)', max_digits=3, null=True)),
                ('detected_intent', models.CharField(blank=True, max_length=100)),
                ('entities', models.JSONField(blank=True, default=dict)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('conversation_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chatbot.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['conversation_id', 'created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='chatbot_cha_user_id_1861d0_idx'), models.Index(fields=['conversation_id', 'created_at'], name='chatbot_cha_convers_f8ca66_idx'), models.Index(fields=['message_type', 'is_processed'], name='chatbot_cha_message_6fe6ff_idx')],
            },
        ),
    ]
